version: '3.8'

services:
  app:
    
    build:
      context: .
      dockerfile: Dockerfile
    
    volumes:
      - .:/app
      - ../model:/app/model
    
    ports:
      - "5000:5000"
    
    command: python app.py